# Generated by Django 5.0.7 on 2024-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(default="default description"),
        ),
    ]
