# Generated by Django 5.0.7 on 2024-07-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="earth", max_length=120),
        ),
    ]
