# Generated by Django 5.0.7 on 2024-07-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0004_remove_profile_name_profile_birthday_profile_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="Postal_code",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="house_number",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="street",
            field=models.CharField(default="", max_length=120),
        ),
    ]
